In [3]:
import numpy as np
from numpy.linalg import eigh, eig
from math import sqrt


def ComputeSVD(A):
    """ 
    Given a matrix A use the eigen value decomposition to compute a SVD
    decomposition. It returns a tuple (U,Sigma,V) of np.matrix objects.
    """
    B = np.matmul(A.transpose(), A)

    E, V = eig(B)

    Sigma = np.zeros((A.shape[1], A.shape[1]))
    np.fill_diagonal(Sigma, np.sqrt(E))

    invSigma = np.zeros((A.shape[1], A.shape[1]))
    np.fill_diagonal(invSigma, 1 / np.sqrt(E))

    U = np.zeros((A.shape[1], A.shape[1]))
    U = (invSigma * (A * V).T).T

    return np.matrix(U), np.matrix(Sigma), np.matrix(V)


def PseudoInverse(A):
    """ 
    Given a matrix A use the SVD of A to compute the pseudo inverse.
    It returns the pseudo inverse as a np.matrix object.
    """
    U, S, V = ComputeSVD(A)

    piS = np.reciprocal(S, where=(np.not_equal(S, np.zeros(S.shape))))  # Pseudoinverses von Sigma berechnen

    return V @ piS @ U.H


def LinearSolve(A, b):
    """ 
    Given a matrix A and a vector b this function solves the linear
    equations A*x=b by solving the least squares problem of minimizing
    |A*x-b| and returns the optimal x.
    """
    psInv = PseudoInverse(A)

    return psInv @ b#%%
import numpy as np
from numpy.linalg import eigh, eig
from math import sqrt


def ComputeSVD(A):
    """
    Given a matrix A use the eigen value decomposition to compute a SVD
    decomposition. It returns a tuple (U,Sigma,V) of np.matrix objects.
    """
    B = np.matmul(A.transpose(), A)

    E, V = eig(B)

    Sigma = np.zeros((A.shape[1], A.shape[1]))
    np.fill_diagonal(Sigma, np.sqrt(E))

    invSigma = np.zeros((A.shape[1], A.shape[1]))
    np.fill_diagonal(invSigma, 1 / np.sqrt(E))

    U = np.zeros((A.shape[1], A.shape[1]))
    U = (invSigma * (A * V).T).T

    return np.matrix(U), np.matrix(Sigma), np.matrix(V)


def PseudoInverse(A):
    """
    Given a matrix A use the SVD of A to compute the pseudo inverse.
    It returns the pseudo inverse as a np.matrix object.
    """
    U, S, V = ComputeSVD(A)

    piS = np.reciprocal(S, where=(np.not_equal(S, np.zeros(S.shape))))  # Pseudoinverses von Sigma berechnen

    return (V @ piS @ U.H)


def LinearSolve(A, b):
    """
    Given a matrix A and a vector b this function solves the linear
    equations A*x=b by solving the least squares problem of minimizing
    |A*x-b| and returns the optimal x.
    """
    psInv = PseudoInverse(A)

    return psInv @ b

In [4]:
# Try the SVD decomposition
A = np.matrix([[1.0, 1.0, 1.0], [1.0, 2.0, 3.0], [1.0, 4.0, 9.0], [1.0, 8.0, 27.0]])
U, Sigma, V = ComputeSVD(A)
print("U:")
print(U)
print("Sigma:")
print(Sigma)
print("V:")
print(V)
print()
print("If the following numbers are nearly zero, SVD seems to be working.")
print(np.linalg.norm(U * Sigma * V.H - A))
print(np.linalg.norm(U.H * U - np.eye(3)))
print(np.linalg.norm(V.H * V - np.eye(3)))
print()

# Try solving a least squares system
b = np.matrix([1.0, 2.0, 3.0, 4.0]).T
x = LinearSolve(A, b)

difference = np.linalg.norm(x - np.linalg.lstsq(A, b, rcond=None)[0])
print("If the following number is nearly zero, " "linear solving seems to be working:", difference)
if np.isclose(difference, 0.0):
    print("✔️ The solution is close to the numpy least squares result.")
else:
    print("❌ The solution seems to be wrong.")#%%
# Try the SVD decomposition
A = np.matrix([[1.0, 1.0, 1.0], [1.0, 2.0, 3.0], [1.0, 4.0, 9.0], [1.0, 8.0, 27.0]])
U, Sigma, V = ComputeSVD(A)
print("U:")
print(U)
print("Sigma:")
print(Sigma)
print("V:")
print(V)
print()
print("If the following numbers are nearly zero, SVD seems to be working.")
print(np.linalg.norm(U * Sigma * V.H - A))
print(np.linalg.norm(U.H * U - np.eye(3)))
print(np.linalg.norm(V.H * V - np.eye(3)))
print()

# Try solving a least squares system
b = np.matrix([1.0, 2.0, 3.0, 4.0]).T
x = LinearSolve(A, b)

difference = np.linalg.norm(x - np.linalg.lstsq(A, b, rcond=None)[0])
print("If the following number is nearly zero, " "linear solving seems to be working:", difference)
if np.isclose(difference, 0.0):
    print("✔️ The solution is close to the numpy least squares result.")
else:
    print("❌ The solution seems to be wrong.")

U:
[[-0.04328203 -0.74576154 -0.50635895]
 [-0.1166556  -0.0414841  -0.6007988 ]
 [-0.32673486  0.63915977 -0.546948  ]
 [-0.93688978 -0.18328554  0.28894516]]
Sigma:
[[30.0685691   0.          0.        ]
 [ 0.          0.42740494  0.        ]
 [ 0.          0.          2.16759711]]
V:
[[-0.04734386 -0.7753102  -0.62980366]
 [-0.30193159  0.61212442 -0.73084951]
 [-0.95215328 -0.15555638  0.26307098]]

If the following numbers are nearly zero, SVD seems to be working.
1.745417488267605e-14
2.906497649210461e-14
6.981760191221845e-15

If the following number is nearly zero, linear solving seems to be working: 1.5115124275036263e-13
✔️ The solution is close to the numpy least squares result.
U:
[[-0.04328203 -0.74576154 -0.50635895]
 [-0.1166556  -0.0414841  -0.6007988 ]
 [-0.32673486  0.63915977 -0.546948  ]
 [-0.93688978 -0.18328554  0.28894516]]
Sigma:
[[30.0685691   0.          0.        ]
 [ 0.          0.42740494  0.        ]
 [ 0.          0.          2.16759711]]
V:
[[-0.0473438